# Конфигурация для Google Cloud Build
# Автоматическая сборка и развертывание в Cloud Run

steps:
  # Сборка Docker образа
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/dashboard:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/dashboard:latest'
      - '.'
    id: 'build-image'

  # Отправка образа в Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/dashboard:$SHORT_SHA'
    id: 'push-image-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/dashboard:latest'
    id: 'push-image-latest'

  # Развертывание в Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dashboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dashboard:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
    id: 'deploy-cloud-run'

# Изображения для сохранения
images:
  - 'gcr.io/$PROJECT_ID/dashboard:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/dashboard:latest'

# Опции сборки
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Таймаут сборки (в секундах)
timeout: '1200s'

